stages:
  - build
  - test

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cache/*
    - cache/Cypress
    - node_modules
    - build

build:
  image: cypress/browsers:node14.17.0-chrome88-ff89
  stage: build
  variables:
    NODE_ENV: "development"
  script:
    - yarn install
    - npx cypress cache path
    - npx cypress cache list
    - yarn build
  artifacts:
    paths:
      - dist

test-unit:
  image: node:alpine
  stage: test
  variables:
    NODE_ENV: "test"
  script:
    - yarn test:unit:ci

test-e2e:
  image: cypress/browsers:node14.17.0-chrome88-ff89
  stage: test
  variables:
    NODE_ENV: "test"
  script:
    - yarn cypress info && yarn cypress verify
    - yarn test:e2e:ci
  artifacts:
    paths:
      - cypress/screeenshots
      - cypress/videos
